### ISSUE TITLE
instructions use "cmus-lyrics-master.zip" rather than "master.zip"

### ISSUE THREAD

**Issue by hobbsy** [hakerdefo/cmus-lyrics#4]
Hi - apologies in advance if I have got this wrong.

The instructions refer to "cmus-lyrics-master.zip" but I think the file is called "master.zip"

eg. this line
```
Extract it,
unzip cmus-lyrics-master.zip
```

should maybe be
`unzip master.zip`

and likewise the cleanup instructions
`rm cmus-lyrics-master.zip`

should be 
`rm master.zip`

**Comment by hobbsy** [comment]
also this line at the top of the instructions:

Obtain sudo privileges and download cmus-lyrics-master.zip

should maybe change to **master.zip**

**Comment by hakerdefo** [comment]
Hi there @hobbsy 
The archive is downloading as **cmus-lyrics-master.zip** when downloaded via both browser and wget at my end. What method did you use to download it?

**Comment by hobbsy** [comment]
Hi - I'm referring to the Instructions in the README.md

==
Installation :

Very easy.

Obtain sudo privileges and download cmus-lyrics-master.zip,

sudo -s
wget https://github.com/hakerdefo/cmus-lyrics/archive/master.zip

Extract it,
unzip cmus-lyrics-master.zip

==

if you hover over the linked file in this part of the README it is called master.zip not cmus-lyrics-master.zip (so the Extract instructions wouldn't work, would need to be unzip master.zip). Just pointing this out in case it helped anyone.

URL:
https://github.com/hakerdefo/cmus-lyrics/archive/master.zip

clickable text for that link "cmus-lyrics-master.zip"

**Comment by hobbsy** [comment]
sorry, to answer your question - the method I just tried was via wget

wget https://github.com/hakerdefo/cmus-lyrics/archive/master.zip

which downloaded a file called master.zip to my desktop

**Comment by hakerdefo** [comment]
I think I've nailed the source of confusion @hobbsy 
In my .**wgetrc** I've following included,
`content_disposition = on`
This option correctly names the downloaded file. So at my end the file was downloading as **cmus-lyrics-master.zip** but since this option is not enabled by default at your end it was downloading as **master.zip**. I've added the `--content-disposition` option in the **README.md**
Thanks for pointing this out!
Cheers!!!
