### ISSUE TITLE
Crashing when opened in tmux for a while

### ISSUE THREAD

**Issue by leana8959** [hakerdefo/cmus-lyrics#9]
As title. Maybe the program kept printing lyrics and ran out of the buffer?
Really appreciate any suggestion to debug/fix the issue.

Léana

**Comment by hakerdefo** [comment]
Hi there @leana8959 

I'm not a tmux user but I tested cmus-lyrics in tmux on my Debian Sid install and it ran as it should, without a glitch. My suggestion to you would be to try cmus-lyrics in tmux  without your ~/.tmux.conf file. There could be something in tmux config file that is causing the issue.

**Comment by leana8959** [comment]
Will try, thank you for the insight :)
